### ISSUE TITLE
load_data.py is not executing

### ISSUE THREAD

**Issue by SameerInnokrish** [iamlemec/patents#4]
Running load_data.py script throws up this error:
Traceback (most recent call last):
  File "load_data.py", line 37, in <module>
    concat_files(args.input, args.output, c, t)
  File "load_data.py", line 16, in concat_files
    first = files[0]
IndexError: list index out of range

**Comment by iamlemec** [comment]
Looks like one of the input files is missing. That script looks in `parsed` for input files and writes the output files in `tables`. What does your `parsed` directory look like? Also, are you passing any arguments when you call `load_data.py`?

**Comment by SameerInnokrish** [comment]
> Looks like one of the input files is missing. That script looks in `parsed` for input files and writes the output files in `tables`. What does your `parsed` directory look like? Also, are you passing any arguments when you call `load_data.py`?

Thanks for your quick response, i had not passed argument - apply after load_data.py, now its working nicely, good work on parsing and fetching patent data
